### ISSUE TITLE
Add named export

### ISSUE THREAD

**Issue by jonaskello** [substack/insert-css#24]
In addition to the default export would it be possible to add a named export `insertCss`? The reason is that typescript has problems with using default exports from commonjs modules.

**Comment by vvo** [comment]
I would say this is an issue typescript need to solve, not every npm module. What do you think?

**Comment by jonaskello** [comment]
The problem is something like an incompatibility between commonjs and es6 modules that typescript uses. There has been several requests over the years to fix it on the typescript repo but all has been declined. But as long as there is a named export it works. You can have a look at how it is done in for example [csjs](https://github.com/rtsao/csjs/blob/master/index.js#L6). I will do a PR also so you can see more in detail.

**Comment by jonaskello** [comment]
The PR is in #25.

**Comment by jonaskello** [comment]
Another way would of course be to publish insert-css as pure es6 modules but I think keeping it as commonjs and adding an extra named export is easier.

**Comment by vvo** [comment]
released as 1.1.0
