### ISSUE TITLE
CSS from another module

### ISSUE THREAD

**Issue by nlwillia** [substack/insert-css#6]
Any suggestion for how to resolve CSS that is located in another module?  insertCSS requires a file system path, but if that's not local to my project, then I have to figure out the path of the module and then the CSS file relative to it.  Except "require" in a browserify project isn't really running in a node environment, so I don't have access to something like require.resolve() in the browser to get details about the module.  I guess the quickest solution is to just copy the CSS file into my project, but I'd prefer to deal with it like any other external dependency.

**Comment by binarykitchen** [comment]
Good question. I have a similar situation ... don't want to run this through gulp nor browserify.

**Comment by vvo** [comment]
no more relevant I believe, we are not tied to FS, browserify can
